In [9]:
import json

import pandas as pd
import numpy as np
import networkx as nx

import torch
from torch_geometric.nn import GATConv, GATv2Conv
from torch_geometric.data import Data
from torch_geometric.datasets import Planetoid
from torch_geometric.loader import GraphSAINTRandomWalkSampler, GraphSAINTNodeSampler
from matplotlib import pyplot as plt

from train_utils import *
from product_graph import *
from torch_geometric.data import HeteroData
from tqdm import tqdm
from torch_geometric.utils import to_dense_adj
from torch.nn import MSELoss
from product_graph import generate_parametric_product_graph
import networkx as nx
from torch_geometric.utils import from_networkx
import torch.nn.functional as F
import torch.nn as nn
from torch_geometric.utils import from_scipy_sparse_matrix

In [47]:
class GATv3Conv(torch.nn.Module):
    def __init__(self, in_channels, out_channels, concat = True, heads=1) -> None:
        super().__init__()
        self.beta = torch.nn.Parameter(torch.tensor(0.5))
        self.conv = GATv2Conv(in_channels, out_channels, heads, concat,add_self_loops=False)

    def forward(self, x, edge_index, edge_weights):
        H, C = self.conv.heads, self.conv.out_channels

        if isinstance(x, torch.Tensor):
            assert x.dim() == 2
            x_l = self.conv.lin_l(x).view(-1, H, C)
            if self.conv.share_weights:
                x_r = x_l
            else:
                x_r = self.conv.lin_r(x).view(-1, H, C)
        else:
            raise TypeError("x must be a Tensor")

        assert x_l is not None
        assert x_r is not None

        # edge_updater_type: (x: PairTensor, edge_attr: OptTensor)
        alpha = self.conv.edge_updater(edge_index, x=(x_l, x_r), edge_attr=None)
        
        
        
        alpha = (1-self.beta) * alpha + self.beta * edge_weights.view(edge_weights.shape[0],1)
        # propagate_type: (x: PairTensor, alpha: Tensor)
        out = self.conv.propagate(edge_index, x=(x_l, x_r), alpha=alpha)

        if self.conv.concat:
            out = out.view(-1, self.conv.heads * self.conv.out_channels)
        else:
            out = out.mean(dim=1)

        if self.conv.bias is not None:
            out = out + self.conv.bias

        return out
    

class GATNN(torch.nn.Module):
    def __init__(self, hidden_size, in_dim, out_dim,in_head = 8,out_head = 1, p =0.6) -> None:
        super().__init__()
        self.hid = hidden_size
        self.in_head = in_head
        self.out_head = out_head
        self.p = p
        
        
        self.conv1 = GATv3Conv(in_dim, self.hid, heads=self.in_head)
        self.conv2 = GATv3Conv(self.hid*self.in_head, out_dim,
                             heads=self.out_head, concat =False)
        self.lin = nn.Linear(4, 1)

    def forward(self, x, edge_index, edge_weight):
        x = self.conv1(x, edge_index, edge_weight)
        #x = F.elu(x)
        x = F.dropout(x, p=self.p, training=self.training)
        x = self.conv2(x, edge_index, edge_weight)
        x = F.dropout(x, p=self.p, training=self.training)
        #out = F.log_softmax(x, dim=1)
        #x = nn.pool.global_mean_pool(x)
        x = x.view(int(x.shape[0]/4), 4)
        x = self.lin(x)
        return x

In [6]:
import pandas as pd
dynamic_data = torch.tensor(np.load("data/preprocessed/dynamic_data.npy", allow_pickle=True))
S = torch.tensor(np.load("data/adjacency/coords_features.npy", allow_pickle=False))


calendar_df = pd.read_csv('data/preprocessed/calendar.csv')
data = Data(x = dynamic_data)
edge_index = torch.nonzero(torch.tensor(S), as_tuple=False).t().contiguous()
edge_weight = S[edge_index[0], edge_index[1]]
data.edge_index = edge_index
data.edge_weight = edge_weight

/var/folders/k7/vcjbn_bd7wdb2g9h92g_pkj80000gn/T/ipykernel_1872/1233144186.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.nonzero(torch.tensor(S), as_tuple=False).t().contiguous()


In [48]:
criterion = MSELoss()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = GATNN(hidden_size=8, in_dim = 1, out_dim = 1).to(device)

loader = GraphSAINTNodeSampler (
    data,
    batch_size=200,
    num_steps=6,
)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)

temporal_adj = np.array([[0, 0, 0, 0],
                [1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 1, 0]])



In [92]:


product_graph = generate_parametric_product_graph(s00 = 0, s01 = 1, s10 = 1, s11 = 1, A_T = temporal_adj, A_N = S.numpy())
print(type(product_graph))
param_edge_idx, param_edge_weight = from_scipy_sparse_matrix(product_graph)



<class 'scipy.sparse._csr.csr_array'>


In [49]:
train_loss = []
for epoch in range(20):
    model.train()
    total_loss = 0
    for i, batch in enumerate(loader):
        batch_loss = 0
        dataset = create_forecasting_dataset(batch.x.T,
                                        splits = None,
                                        pred_horizen= 1,
                                        obs_window= 4,
                                        verbose = 0)
        batch_sample = Data(x = torch.tensor(dataset['trn']['data']), y = torch.tensor(dataset['trn']['labels']), 
                            edge_index= batch.edge_index, edge_weight = batch.edge_weight)


        batch_adj = to_dense_adj(batch_sample.edge_index, edge_attr=batch_sample.edge_weight).squeeze(dim = 0)
        

        batch_adj = batch_adj.numpy()
        
        product_graph = generate_parametric_product_graph(s00 = 0, s01 = 1, s10 = 1, s11 = 1, A_T = temporal_adj, A_N = batch_adj, spatial_graph = None)
        product_edge_index, product_edge_weight = from_scipy_sparse_matrix(product_graph)
        
        
        batch_x =batch_sample.x.reshape(batch_sample.x.shape[0], batch_sample.x.shape[1]* batch_sample.x.shape[2], 1)
        
        batch_y = batch_sample.y.reshape(batch_sample.y.shape[0], batch_sample.y.shape[1])
        
        for i in range(batch_sample.x.shape[0]):
            
            optimizer.zero_grad()
            out = model(batch_x[i].float(), product_edge_index,product_edge_weight.float())
            print(f'out shape: {out.shape} \n y shape {batch_y[i].shape}')
            print(out)
            loss = criterion(out, batch_y[i].float())
            batch_loss += loss
        
            loss.backward()
            optimizer.step()
            
        total_loss += batch_loss
        print(f'Epoch: {epoch} Batch Loss: {batch_loss}')
    train_loss.append(total_loss)

out shape: torch.Size([186, 1]) 
 y shape torch.Size([186])
tensor([[-2.4484e+03],
        [ 1.1779e+03],
        [-6.1201e+03],
        [-3.3358e+04],
        [-1.3436e+04],
        [-3.9544e-02],
        [-7.8091e+03],
        [-3.9544e-02],
        [-3.9544e-02],
        [-3.9544e-02],
        [ 9.3866e+03],
        [-4.4019e+04],
        [ 1.1130e+04],
        [ 1.0879e+04],
        [ 1.2029e+04],
        [ 2.3682e+04],
        [ 1.3741e+04],
        [-2.8038e+04],
        [-3.9544e-02],
        [-2.3728e+04],
        [-1.0679e+04],
        [-2.2080e+03],
        [-4.9725e+04],
        [ 5.2439e+03],
        [-3.5850e+04],
        [-3.0536e+04],
        [-3.1499e+04],
        [-1.2110e+04],
        [-1.2366e+04],
        [ 1.5755e+04],
        [ 9.6687e+03],
        [ 8.4861e+03],
        [-3.9544e-02],
        [ 6.8104e+03],
        [ 6.0888e+03],
        [-2.9300e+03],
        [-3.9544e-02],
        [-9.9542e+03],
        [-3.0964e+04],
        [-2.7462e+04],
        [-1.2173e+04

/opt/anaconda3/envs/ml4g/lib/python3.11/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([186])) that is different to the input size (torch.Size([186, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


out shape: torch.Size([186, 1]) 
 y shape torch.Size([186])
tensor([[-1.2036e+03],
        [-1.5896e+04],
        [-4.1674e+03],
        [-1.3991e+04],
        [-8.0662e+03],
        [-1.0776e+04],
        [-4.8104e+03],
        [-2.2613e+04],
        [ 3.4018e+03],
        [-2.0761e+04],
        [-5.0732e+03],
        [ 2.7038e+02],
        [-1.2399e+04],
        [-3.2393e+04],
        [ 8.3938e+03],
        [-4.1842e+04],
        [-1.0739e+04],
        [-3.5225e+04],
        [-4.6278e+03],
        [-7.4879e+03],
        [-6.4407e+03],
        [ 2.7841e+03],
        [-1.3964e+04],
        [-2.4340e+04],
        [ 1.0092e+04],
        [-2.9629e+03],
        [-2.6679e+04],
        [-5.5458e+03],
        [ 4.5160e+03],
        [-7.9909e+03],
        [-1.0032e+04],
        [-4.2451e+03],
        [ 3.4391e+03],
        [-1.0104e+04],
        [ 1.4138e+03],
        [-2.3063e+04],
        [-1.0174e+04],
        [-8.5272e+03],
        [ 4.1147e+03],
        [-1.3522e+04],
        [ 2.2245e+03

KeyboardInterrupt: 

In [114]:
print(out[:10])
print(batch_y[0])

tensor([[ 2.2100e-01],
        [ 1.3513e+03],
        [ 5.9633e+02],
        [ 7.5958e+02],
        [ 4.6309e+02],
        [ 1.1660e+03],
        [ 1.0380e+03],
        [ 7.7342e+02],
        [-7.0580e+01],
        [ 2.1796e+02]], grad_fn=<SliceBackward0>)
tensor([125, 300, 129,  80, 295,  60, 199,  81, 225,  85, 299,  80,  36,  99,
         50, 167, 289, 469,  80, 200, 354, 295, 228, 299, 140, 150, 125, 125,
        139, 225, 199, 249, 145, 100, 450, 300, 170, 137, 116, 150, 600, 149,
        197, 260, 200, 155, 155,  99, 139, 228, 199, 129, 155, 220, 110, 251,
        199, 160, 150, 195, 228, 231, 150, 279, 135, 189, 225, 200, 300, 265,
        299, 207, 305, 189, 186, 150, 199, 255, 130, 169, 139, 266, 225,  90,
        224, 194, 300,  60,  82,  78, 100, 200, 249, 149, 200, 457, 571, 177,
        150, 199, 275, 129, 179, 175, 242, 157, 160, 159, 299, 165, 115, 139,
        230, 499, 179, 690, 537, 150, 259, 375,  91, 259, 199, 139, 250, 185,
        239, 329, 231, 231, 125, 179, 109

In [76]:
print(out.shape[0]/ 4)

193.0


In [ ]:
model.eval()
_, pred = model(x_test).max(dim=1)
correct = float(pred.eq(y_test).sum().item())
acc = correct / x_test.sum().item()
print('Accuracy: {:.4f}'.format(acc))

In [201]:
x = torch.tensor([[100], 
                  [1],
                  [2],
                  [3]]).float()

edge_index = torch.tensor([[0, 1, 1, 2, 3, 2], 
                           [1, 0, 2, 1, 2, 3]])

edge_weights = torch.tensor([[0.3],
                             [0.3],
                             [0.9],
                             [0.9],
                             [0.1],
                             [0.1]])

gat_net(x, edge_index, edge_weights)

tensor([[-5.4292],
        [-0.9369],
        [-4.6689],
        [-0.5501]], grad_fn=<AddBackward0>)